### ISSUE TITLE
Required parameter name incorrect... 

### ISSUE THREAD

**Issue by allyssonf** [ibm-cloud-security/app-id-sample-node#13]
On sample code that reads localdev-config.json we have this array definition:

`const requiredParams = ['clientId', 'secret', 'tenantId', 'oauthServerUrl', 'profilesUrl'];`

But after AppID service configuration, the generated credentials have
 oauthServerUrl written as follows:

`"oAuthServerUrl": "https://us-south.appid.cloud.ibm.com/oauth/v4/XYZ"`

Which leads to a failure on loading config file for local development.

**Comment by KlutzyBubbles** [comment]
Hi,

I may be a bit late but i just checked most sources i can find that reference that field and all of them are generated or listed as "oauthServerUrl".

I think this issue should be closed as it isn't really an issue.
